# Generated by Django 5.0.6 on 2024-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_color_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandMark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
